Create DATABASE Worlds;
Use Worlds;

CREATE TABLE REGION (
WORLDS INT PRIMARY KEY,
NAME VARCHAR(50),
AGE INT
);
INSERT INTO REGION (WORLDS,NAME,AGE) VALUES
(1,'TOSHMAT',50),
(2, 'BEKMAT', 60),
(3, 'KETMON', 20);
